// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSECe1vgbXYEN7uuMecPsZ67OQchlCVlg',
    appId: '1:809899030115:web:9c15e4f446fa7d09086a56',
    messagingSenderId: '809899030115',
    projectId: 'auth-5da9a',
    authDomain: 'auth-5da9a.firebaseapp.com',
    storageBucket: 'auth-5da9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPpWuX1jAgQqxR2POLt_eXMzeq_sXExU',
    appId: '1:809899030115:android:df6b435dd0a3146a086a56',
    messagingSenderId: '809899030115',
    projectId: 'auth-5da9a',
    storageBucket: 'auth-5da9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-t8KOTJ0g6NSXRtwtL9t7GDBOUmB47gM',
    appId: '1:809899030115:ios:67dadfc480adbbcf086a56',
    messagingSenderId: '809899030115',
    projectId: 'auth-5da9a',
    storageBucket: 'auth-5da9a.appspot.com',
    iosClientId: '809899030115-8n1och4embqh4v6tnj2a4hegcucdc4pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.authLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-t8KOTJ0g6NSXRtwtL9t7GDBOUmB47gM',
    appId: '1:809899030115:ios:67dadfc480adbbcf086a56',
    messagingSenderId: '809899030115',
    projectId: 'auth-5da9a',
    storageBucket: 'auth-5da9a.appspot.com',
    iosClientId: '809899030115-8n1och4embqh4v6tnj2a4hegcucdc4pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.authLearn',
  );
}
